name = "nodeauth-wiki"
main = "src/index.ts"
compatibility_date = "2026-03-17"

workers_dev = false
preview_urls = false

[[routes]]
pattern = "wiki.nodeauth.io/*"
zone_name = "nodeauth.io"

[assets]
directory = "docs/.vitepress/dist"
binding = "ASSETS"

[observability]
enabled = false

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false

