name = "nodeauth-wiki"
main = "src/index.ts"
compatibility_date = "2026-03-17"

workers_dev = false
preview_urls = false

[assets]
directory = "docs/.vitepress/dist"
binding = "ASSETS"

[[routes]]
pattern = "wiki.nodeauth.io/*"
zone_name = "nodeauth.io"

[observability]
enabled = true
